PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Controllers/CompraController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class CompraController : Controller
    {
        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Result result = BL.Compra.GetAll();
            ML.Compra compra = new ML.Compra();
            compra.Compras = result.Objects;
            return View(compra);
        }
        [HttpGet]
        public IActionResult Comprar()
        {
            ML.Result result = BL.Producto.GetAll();
            ML.Producto producto = new ML.Producto();
            producto.Productos = result.Objects;
            return View(producto);
        }
        [HttpPost]
        public IActionResult Comprar(int idProducto, int dineroIngresado)
        {
            ML.Result result = BL.Producto.GetById(idProducto);
            ML.Producto producto = (ML.Producto)result.Object;
            if(producto.Precio <= dineroIngresado)
            {   
                int cambio = dineroIngresado - int.Parse(producto.Precio.ToString("0"));
                if (cambio > 0)
                {
                    ML.Result resultDenominaciones = BL.Cambio.GetDineroDisponible();
                    ML.Cambio demoninaciones = (ML.Cambio)resultDenominaciones.Object;
                    ObtenerDenominaciones(cambio, demoninaciones);
                    //Validar que las denominaciones seleccionadas cubran el total del cambio a devolver.
                    if(cambio == (demoninaciones.Monedas10 * 10 + demoninaciones.Billetes50 * 50 + demoninaciones.Billetes100 * 100))
                    {
                        ML.Compra compra = new ML.Compra();
                        compra.Producto = new ML.Producto();
                        compra.Producto.IdProducto = idProducto;
                        compra.Ingreso = dineroIngresado;
                        compra.Cambio = cambio;
                        //Realizar la compra
                        ML.Result resultOperacion = BL.Compra.Add(compra);
                        if (resultOperacion.Correct)
                        {
                            ViewBag.Mensaje = $"Gracias por tu compra :) Tu cambio: {cambio}. \nMonedas de 10: {demoninaciones.Monedas10}. \nBilletes 50: {demoninaciones.Billetes50}. \nBilletes de 100: {demoninaciones.Billetes100}";
                        }
                        else
                        {
                            ViewBag.Mensaje = resultOperacion.Message;
                        }
                    }
                    else
                    {
                        ViewBag.Mensaje = "Lo sentimos :( La maquina no cuenta con las denominaciones necesarias para dar tu cambio. Se te devolverá el dinero ingresado.";
                    }
                }
                else
                {
                    ML.Compra compra = new ML.Compra();
                    compra.Producto = new ML.Producto();
                    compra.Producto.IdProducto = idProducto;
                    compra.Ingreso = dineroIngresado;
                    compra.Cambio = cambio;
                    //Realizar la compra
                    ML.Result resultOperacion = BL.Compra.Add(compra);
                    if (resultOperacion.Correct)
                    {
                        ViewBag.Mensaje = "Gracias por su compra. Vuelva pronto :)";
                    }
                    else
                    {
                        ViewBag.Mensaje = resultOperacion.Message;
                    }
                }
            }
            else
            {
                ViewBag.Mensaje = "El dinero ingresado no es suficiente para cubrir el total de la compra :(";
            }
            return PartialView("Modal");
        }

        //Método para obtener las denominaciones del cambio a devolver.
        private ML.Cambio ObtenerDenominaciones(int cambioSaliente, ML.Cambio cambio)
        {
            Dictionary <int,int> monedasDisponibles = new Dictionary<int, int> 
            {
                { 100, cambio.Billetes100 },
                { 50, cambio.Billetes50 },
                { 10, cambio.Monedas10 }
            };

            List<int> denominaciones = new List<int>(monedasDisponibles.Keys);

            Dictionary<int, int> resultado = new Dictionary<int, int>
            {
                { 100, 0 },
                { 50, 0 },
                { 10, 0 }
            };

            foreach(var denominacion in denominaciones)
            {
                int cantidadDisponible = monedasDisponibles[denominacion];
                int cantidadMonedas = Math.Min(cambioSaliente / denominacion, cantidadDisponible);
                if (cantidadMonedas > 0)
                {
                    resultado[denominacion] += cantidadMonedas;
                    cambioSaliente -= cantidadMonedas * denominacion;
                    monedasDisponibles[denominacion] -= cantidadMonedas;

                    if(cambioSaliente == 0)
                    {
                        break;
                    }
                }
            }
            cambio.Monedas10 = resultado[10];
            cambio.Billetes50 = resultado[50];
            cambio.Billetes100 = resultado[100];
            return cambio;
        }
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Views/Compra/Comprar.cshtml
@model ML.Producto
@{
    ViewData["Title"] = "Comprar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Comprar</h1>
<hr />
<div>
    <form method="post" action="@Url.Action("Comprar","Compra")">
        <table class="table table-dark table-hover text-center">
            <thead>
                <tr>
                    <th>Tipo</th>
                    <th>Precio</th>
                    <th>Selección</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Producto producto in Model.Productos)
                {
                    <tr>
                        <td>@producto.Tipo</td>
                        <td>@producto.Precio</td>
                        <td class="d-flex justify-content-center">
                            <div class="form-check">
                                <input onclick="ActualizarModal('@producto.Tipo',@producto.Precio)" value="@producto.IdProducto" class="form-check-input" type="radio" name="idProducto" id="flexRadioDefault1">
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Comprar
            </button>
        </div>
        <!-- Modal -->
        <div class="modal fade text-black" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header text-center">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Resumen</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <label>Tipo</label><br />
                        <label id="txtTipo"></label><br /><br />

                        <label>Precio</label><br />
                        <label id="txtPrecio"></label><br /><br />

                        <label>Ingrese dinero</label>
                        <div class="input-group flex-nowrap" style="width:120px">
                            <span class="input-group-text" id="addon-wrapping">$</span>
                            <input name="dineroIngresado" class="form-control" placeholder="0.00" aria-label="Dinero" aria-describedby="addon-wrapping">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-success">Comprar</button>
                    </div>
                </div>
            </div>
        </div>
        <!------------->
    </form>
</div>
<script type="text/javascript">
    function ActualizarModal(tipo, precio) {
        document.getElementById('txtTipo').innerHTML = tipo;
        document.getElementById('txtPrecio').innerHTML = precio;
    }
</script>

PL/Views/Compra/GetAll.cshtml
@model ML.Compra
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Todas las compras</h1>
<hr />
<div>
    <a class="btn btn-success" href="@Url.Action("Comprar","Compra")">Nueva compra</a>
</div>
<hr />
<div class="container">
    @if(Model.Compras != null)
    {
        if(Model.Compras.Count > 0)
        {
            <table class="table table-dark table-hover text-center">
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Ingreso</th>
                        <th>Cambio</th>
                        <th>Total</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(ML.Compra compra in Model.Compras)
                    {
                        <tr>
                            <td>@compra.Producto.Tipo</td>
                            <td>@compra.Ingreso</td>
                            <td>@compra.Cambio</td>
                            <td>@compra.Total</td>
                            <th><a class="btn btn-danger"><i class="fa-solid fa-circle-minus"></i></a></th>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div role="alert" class="alert alert-warning">
                No hay compras registradas.
            </div>
        }
    }
</div>

PL/Views/Compra/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Continuar", "GetAll", "Compra", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body style="background-color:black" class="text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra" asp-action="GetAll">Compras</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>